# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 774)
        MainWindow.setMaximumSize(QtCore.QSize(962, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(200)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_mask_on = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_mask_on.setMaximumSize(QtCore.QSize(361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_mask_on.setFont(font)
        self.radioButton_mask_on.setObjectName("radioButton_mask_on")
        self.horizontalLayout.addWidget(self.radioButton_mask_on)
        self.radioButton_mask_off = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_mask_off.setMaximumSize(QtCore.QSize(365, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButton_mask_off.setFont(font)
        self.radioButton_mask_off.setObjectName("radioButton_mask_off")
        self.horizontalLayout.addWidget(self.radioButton_mask_off)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ch1 = MplWidget(self.centralwidget)
        self.ch1.setMaximumSize(QtCore.QSize(681, 231))
        self.ch1.setObjectName("ch1")
        self.verticalLayout.addWidget(self.ch1)
        self.progressBar_ch1 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_ch1.setMaximumSize(QtCore.QSize(681, 23))
        self.progressBar_ch1.setProperty("value", 0)
        self.progressBar_ch1.setObjectName("progressBar_ch1")
        self.verticalLayout.addWidget(self.progressBar_ch1)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ch2 = MplWidget(self.centralwidget)
        self.ch2.setMaximumSize(QtCore.QSize(681, 231))
        self.ch2.setObjectName("ch2")
        self.verticalLayout_2.addWidget(self.ch2)
        self.progressBar_ch2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_ch2.setMaximumSize(QtCore.QSize(681, 23))
        self.progressBar_ch2.setProperty("value", 0)
        self.progressBar_ch2.setObjectName("progressBar_ch2")
        self.verticalLayout_2.addWidget(self.progressBar_ch2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.simulate_ch1 = QtWidgets.QPushButton(self.centralwidget)
        self.simulate_ch1.setMaximumSize(QtCore.QSize(93, 28))
        self.simulate_ch1.setSizeIncrement(QtCore.QSize(93, 28))
        self.simulate_ch1.setObjectName("simulate_ch1")
        self.horizontalLayout_2.addWidget(self.simulate_ch1)
        self.export_ch1 = QtWidgets.QPushButton(self.centralwidget)
        self.export_ch1.setMaximumSize(QtCore.QSize(93, 28))
        self.export_ch1.setObjectName("export_ch1")
        self.horizontalLayout_2.addWidget(self.export_ch1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 258, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.simulate_ch2 = QtWidgets.QPushButton(self.centralwidget)
        self.simulate_ch2.setMaximumSize(QtCore.QSize(93, 28))
        self.simulate_ch2.setSizeIncrement(QtCore.QSize(93, 28))
        self.simulate_ch2.setObjectName("simulate_ch2")
        self.horizontalLayout_3.addWidget(self.simulate_ch2)
        self.export_ch2 = QtWidgets.QPushButton(self.centralwidget)
        self.export_ch2.setMaximumSize(QtCore.QSize(93, 28))
        self.export_ch2.setObjectName("export_ch2")
        self.horizontalLayout_3.addWidget(self.export_ch2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 158, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_mask_on.setText(_translate("MainWindow", "Simulate with mask applied on "))
        self.radioButton_mask_off.setText(_translate("MainWindow", "Simulate without mask applied on "))
        self.progressBar_ch1.setFormat(_translate("MainWindow", "%p%"))
        self.progressBar_ch2.setFormat(_translate("MainWindow", "%p%"))
        self.simulate_ch1.setText(_translate("MainWindow", "Simulate"))
        self.export_ch1.setText(_translate("MainWindow", "Export"))
        self.simulate_ch2.setText(_translate("MainWindow", "Simulate"))
        self.export_ch2.setText(_translate("MainWindow", "Export"))

from mplwidget import MplWidget
